### ISSUE TITLE
[V2] Validate not called before facet checked

### ISSUE THREAD

**Issue by saulshanabrook** [Yomguithereal/baobab#335] opened 2015-08-31 17:16 UTC
If I add a validation function, I found that the function is not called before some facets are recalculated. For example, if I call `tree.set({})`, which fails validation, it doesn't even hit the `validate` function before erroring out because the a facet errored because the path wasn't available.

```
	TypeError: Cannot read property 'map' of undefined
	    at Baobab.state.local.$allCueNames (/Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/test/unit/main.js:33610:2121)
	    at Facet.get (/Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/test/unit/main.js:38047:31)
	    at Facet.update (/Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/test/unit/main.js:38028:106)
	    at Baobab.Facet.listener (/Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/test/unit/main.js:37980:16)
	    at Baobab.Emitter.emit (/Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/test/unit/main.js:36012:21)
	    at Baobab.update (/Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/test/unit/main.js:35389:13)
	    at Cursor.(anonymous function) [as set] (/Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/test/unit/main.js:36883:23)
	    at Baobab._this.(anonymous function) [as set] (/Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/test/unit/main.js:35240:34)
```

I added logging to `validate`, which normally works, but here it doesn't reach that, so I know its not even calling validate before creating those facets.

**Comment by saulshanabrook** [comment] 2015-08-31 17:16
I guess you might *want* `validate` to happen after the facets have been populated.

Was this intended?

**Comment by saulshanabrook** [comment] 2015-08-31 17:19
As I workaround, I am using es6's default parameters as a safegaurd against missing data:

```javascript
    '$allCueNames': [
      ['synced', 'cues'],
      (cues = []) => cues.map(p => p.name)
    ],
```

**Comment by Yomguithereal** [comment] 2015-09-01 09:05
I should check that indeed @saulshanabrook. Seems like a bug.

Concerning the es6 default parameter, does it work since the facets implementation will be likely to pass `undefined` to the function rather than not passing it?

**Comment by saulshanabrook** [comment] 2015-09-01 12:16
Yeah seemed to work for me.

**Comment by Yomguithereal** [comment] 2015-09-01 12:21
Ok, your issue exists because the validation is run on the asynchronous updates when the changes are committed, not on write. But I must agree this behavior should be discussed though.

**Comment by Yomguithereal** [comment] 2015-09-15 15:22
Any update about this @saulshanabrook?

**Comment by saulshanabrook** [comment] 2015-09-15 20:21
Has the behavior been changed? I could add a test case for this scenario, if the desired behavior is to validate before calculating facets. Would that be helpful?

**Comment by Yomguithereal** [comment] 2015-09-16 09:55
The issue is not about facet calculation but rather with the fact that validation is run on update rather than on write event. But, on a slightly different matter, is the validation still really needed as part of Baobab's core?

**Comment by saulshanabrook** [comment] 2015-09-16 13:03
I am not sure. I need to validate a path at some point, but I don't really care where it is. I brought up adding validation to cerebral (https://github.com/christianalfoni/cerebral/issues/77) and @christianalfoni [said](https://github.com/christianalfoni/cerebral/issues/77#issuecomment-139744679):

> As both Baobab and tComb supports validation of state I have a gut feeling that this should belong to the model package. Are there any issues now using the internal tools of the model packages? Like Baobab and tComb?

Do you see any compelling reasons to have it in the controller (cerebral) instead of the model (baobab)?

**Comment by saulshanabrook** [comment] 2015-09-16 13:05
@Yomguithereal As to this specific issue, is there a possible solution or is this actually intended behavior? Should facet's be recalculated before validation happens, or vice versa?

**Comment by Yomguithereal** [comment] 2015-09-16 13:07
The possible solution is just to run validation on write rather than on update. You'll just lose some performance in some cases because validation will run more frequently. That's all.

**Comment by saulshanabrook** [comment] 2015-09-16 13:12
What is the difference between write and update?

**Comment by Yomguithereal** [comment] 2015-09-16 13:17
Write is synchronous and happens whenever a setter function is used by the tree or a cursor. The update is asynchronous by default and notify of a whole transaction on the tree which might be comprised of several writes.

**Comment by saulshanabrook** [comment] 2015-09-16 13:33
Hm, another advantage of keeping the existing behavior (running validation on update) is so that you can do multiple writes that individually create an invalid tree, but at the end make something valid.

So are facet's calculated after every write?

**Comment by Yomguithereal** [comment] 2015-09-16 13:34
Yes, facets are updated after every write (won't be calculated before you actually get them however so they remain lazy).

**Comment by Yomguithereal** [comment] 2015-09-16 13:35
Is your above error still here on the latest dev version by the way?

**Closed** 2015-09-28 14:53 UTC
Labels: bug
