### ISSUE TITLE
Baobab v2 proposal

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab#278] opened 2015-07-08 20:47 UTC
## Baobab v2 proposal

This document is a proposal for the release of Baobab v2. Some things need to be discussed here before we can advance, and this is really the point of this issue to discuss.

### Installation

You can install the latest published dev version of the v2 with:

```bash
npm install baobab@dev
```

Updated `baobab-react` will soon follow and soon will be created `baobab-deku`.

### Immutability

The tree is now immutable by default. My advice about this is to develop your apps with immutability (using `"use strict" so it would throw if you attempt to mutate) on and to disable it for production to see a welcome performance boost (I'd say ~30%).

### Syncwrite

The tree now write synchronously only but will continue firing its update events asynchronously for obvious performance reasons.

### Update specifications & transactions

Update specifications have been dropped in favor of a simpler spec.

An update is now internally:

```js
{path: [...], type: 'set', value: 'Hey'}
```

Furthermore, the tree's update events now expose the full detail of the transactions so you can replay them elsewhere or display debugging information etc. (@christianalfoni :-) )

### No more default limit on cursor's history

By default, cursor's history limit is set to `Infinity`.

### Cursor setters

Cursors' setters now longer return themselves. This was made so you can chain them but now that we should embrace immutability, returning the affected node seems way more pratical than having to write then get the affected node to carry on your operations.

### push/unshift & concat method

Dropped the strange push/unshift concat-like behavior.

### Facets rework

Following the discussion in #240, facets are now to be defined within the tree itself using keys starting with a dollar by convention.

*Example*

```js
const tree = new Baobab({
  data: {
    messages: [
      {from: 'John', text: 'Hey'},
      {from: 'Jack', text: 'Ho'}
    ],
    $fromJohn: {
      cursors: {
        messages: ['data', 'messages'],
        get: function({messages}) {
          return messages.filter(m => m.from === 'John');
        }
      }
    }
  }
});
```

This way, there is only one way to select and get data in the tree and one can just create cursor on computed data and even select/get data beyond them:

```js
var cursor = tree.select('data', '$fromJohn', 0, 'text');
```

*Disclaimer*

The current dev version only allows to define facets at the tree's instantiation but v2 will allow you to modify/set/unset facets on the fly by using the tree's setters like you would normally.

The only problem there is that once the facet has been define, you can't really access its definition anymore.

Facets remain of course lazy on get and won't be computed until you really need them.

### Alternative facet definition syntax

```js
const tree = new Baobab({
  data: {
    messages: [
      {from: 'John', text: 'Hey'},
      {from: 'Jack', text: 'Ho'}
    ],
    $fromJohn: [
      ['data', 'messages'],
      function(messages) {
        return messages.filter(m => m.from === 'John');
      }
    ]
  }
});
```

### tree/cursor.serialize

Since there is now computed data sitting within the tree itself, one wouldn't want to get it when "serializing" the data, for instance when you would need to save it to the `localStorage`, for instance. This is exactly what the `cursor.serialize` method does.

The method would return data at any cursor but carefully avoiding any computed data.

### tree/cursor.project

Naming alert here! I did not find a better name. This method will probably used only internally but still. I'll take any better name.

```js
var data = cursor.project({
  messages: ['data', 'messages'],
  user: ['user']
});
// Will return an object with the related data

var data = cursor.project([
  ['data', 'messages'],
  ['user']
]);
// Will return an array with the related data
```

### tree.watch

Used to watch a collection of path in the tree and fire updates if any of the paths is affected. (Used by `baobab-react`).

### Dropped $cursor

No more silly `$cursor` sugar.

### Misc

The code has been rewritten in ES6 and is now fully self-documented.

`emmett` has been updated to its latest version.

## Full Provisional v2 Changelog

* The tree is now immutable by default.
* Cursor's setters method won't return themselves but rather the affected node now.
* Adding `cursor.concat`.
* Adding the `cursor.serialize` method.
* Adding the `cursor.project` method.
* Changing the way you can define computed data in the tree, aka "facets". Facets are now to be defined within the tree itself and can be accessed using the exact same API as normal data.
* Adding an alternative facet definition syntax for convenience.
* Dropped the `syncwrite` option. The tree is now writing synchronously but still emits its updates asynchronously by default.
* Max number of records is now set to `Infinity` by default, meaning there is no limit.
* Update events are now exposing the detail of each transaction so you can replay them elsewhere.
* Fixing `cursor.push/unshift` behavior.
* Dropped the `$cursor` helper.
* Dropped the `update` specs for a simpler transaction syntax.
* Updated `emmett` to `3.1.0`.
* ES6 codebase rewrite.
* Full code self documentation.

**Comment by tnrich** [comment] 2015-07-08 21:28
Hey @Yomguithereal , I'm excited to start trying out v2. One thing that I was hoping was going to be changed/fixed was #264: Facet not being updated when listening facet updated. 

However, I made a little example here to test out whether this would be fixed, and I don't think it has been:
```
// to use:
// babel test.js --out-file test-compiled.js
// node test-compiled.js
var Baobab = require('baobab');
var assign = require('object-assign');
const tree = new Baobab({
  data: {
    messages: [
      {from: 'John', text: 'Hey'},
      {from: 'Jack', text: 'Ho'}
    ],
    $fromJohn: {
      cursors: {
        messages: ['data', 'messages'],
      },
      get: function({messages}) {
        return messages.filter(m => m.from === 'John');
      }
    },
    $fromJohnWithLove: {
      cursors: {
        messages: ['data', '$fromJohn'],
      },
      get: function({messages}) {
        return messages.map(m => assign({},m,{text: m.text+', Love John'}));
      }
    }
  }
});
console.log('Print the two facets :');
console.log('$fromJohn: ',tree.select('data', '$fromJohn', 0, 'text').get());
console.log('$fromJohnWithLove: ', tree.select('data', '$fromJohnWithLove', 0, 'text').get());

console.log('update the message[0].text');
tree.select('data', 'messages', 0, 'text').set('Hi there');
console.log('Print the two facets again: ');
console.log('$fromJohn: ',tree.select('data', '$fromJohn', 0, 'text').get());
console.log('$fromJohnWithLove: ', tree.select('data', '$fromJohnWithLove', 0, 'text').get());
```

Here's the output I get when I run this script:
```
Print the two facets :
$fromJohn:  Hey
$fromJohnWithLove:  Hey, Love John
update the message[0].text
Print the two facets again: 
$fromJohn:  Hi there
$fromJohnWithLove:  Hey, Love John
```

So, it looks like the 2nd facet isn't being updated correctly still. Am I missing something here that would trigger the 2nd facet to be updated correctly?

**Comment by Yomguithereal** [comment] 2015-07-08 21:36
I am fixing this problem right now @tnrich. Should be working soon hopefully :-).

**Comment by tnrich** [comment] 2015-07-08 21:41
That's awesome news!

**Comment by tnrich** [comment] 2015-07-08 21:43
If other people want a base repo to make little tests on they're welcome to clone: 
https://github.com/tnrich/baobabV2test

**Comment by Yomguithereal** [comment] 2015-07-08 21:57
Just fixed the problem @tnrich. And published an updated dev version on npm.

**Comment by marbemac** [comment] 2015-07-08 22:38
This is awesome! Thank you - I'll be trying it out shortly. 

Separately, @tnrich I'm using Baobab v1 and recursive facets seem to working OK. However, I have autoCommit off, asynchronous off, and syncwrite on. When testing this via console.log, I'd using those settings because it's easy for the log to output before the change has been committed to the tree. I think?

**Comment by marbemac** [comment] 2015-07-08 22:55
About to check it out - @Yomguithereal should this work out of the box w baobab-react?

**Comment by Yomguithereal** [comment] 2015-07-08 22:59
@marbemac I dont think the current version of baobab-react would work with v2 currently. But I will soon update it.

**Comment by marbemac** [comment] 2015-07-08 23:38
Awesome, looking forward to it - thanks.

**Comment by tnrich** [comment] 2015-07-09 05:35
Awesome thanks @Yomguithereal !
Hmm interesting to hear @marbemac . For some reason they didn't work all the time for me in v1. I had autoCommit on and async on as well.

**Comment by ivan-kleshnin** [comment] 2015-07-09 10:33
> Append and prepend method

In my mind `append` is the same as `push` so if you provide both `append` and `prepend` methods `push` shouldn't really exist. Making both available and holding different semanthics is confusing IMO.
What you call `push` is generally called `concat` so I bet it would be a better name.

My expectations:

```js
cursor.get() >>> [1, 2]
cursor.append(3) >>> [1, 2, 3]
cursor.append([4, 5]) >>> [1, 2, 3, [4, 5]]
cursor.prepend(6) >>> [6, 1, 2, 3, [4, 5]]

cursor.concat([7]) >>> [6, 1, 2, 3, [4, 5], 7]
```

To be able to "concat in the beginning" we also need `reverse()`.

```js
cursor.reverse() >>> [2, 1]
cursor.concat([0, -1]) >>> [2, 1, 0, -1]
cursor.reverse() >>> [-1, 0, 1, 2]
```

Btw, what is your policy about wrong type for operations? This should be mentioned in the docs IMO.

**Comment by Yomguithereal** [comment] 2015-07-09 12:02
Hello @ivan-kleshnin,
Concerning the wrong type operation, it will throw synchronously an helpful error.

I am still thinking about the append/prepend conundrum but the reverse thing is not a viable option perf-wise.

What I could do in the future, however, is to permit the addition of custom operation such as reverse, for instance.

**Comment by Yomguithereal** [comment] 2015-07-09 16:50
Discussion concerning the future of `baobab-react`: Yomguithereal/baobab-react#66.

**Comment by marbemac** [comment] 2015-07-09 19:55
Would something like the below be possible? Kind of like a dynamic facet, that only fire's the update event if the particular piece of data it's listening to changes? As it stands now, facets have to listen to the entire data collection, and so will re-run and fire an update if a completely unrelated message is changed.

Probably not possible, and not strictly necessary, but would be really cool, and save on updates/re-renders. Of course if the data is immutable and you build your components right, the re-render shouldn't matter as the object returned from the facet won't have changed.

```js
const tree = new Baobab({
  data: {
    messages: {
      1: {from: 'John', text: 'Hey'},
      2: {from: 'Jack', text: 'Ho'}
    },
    currentMessage: {
        id: 2,
        $data: {
          cursors: {
            message: ['data', 'messages', currentMessage.id],
            get: function({message}) {
              return message;
            }
          }
        }
      }
    }
  }
});
```

**Comment by marbemac** [comment] 2015-07-09 19:55
Separately, should the get function be nested in the cursors object?

**Comment by frontengineer** [comment] 2015-07-10 00:22
@Yomguithereal Hi. I may have missed this...but any thoughts on where in the life cycle backend/persistence calls best fit?  To elaborate...some suggest putting async call/results in the "Actions...then push data to Flux store for component consumption." I was wondering if Baobab facets is intended for all or part of that.  I am new to your library...I like it over most Flux I've seen...and have so far only done a basic todo with v1. Thanks for all the work you are doing.

**Comment by ivan-kleshnin** [comment] 2015-07-10 08:25
> I am still thinking about the append/prepend conundrum but the reverse thing is not a viable option perf-wise.

I think it shouldn't be your concern. Just let the developer decide about what operations are acceptable and what are not. You can't prevent people ignorant of computer science to shoot in their legs IMO.

**Comment by Yomguithereal** [comment] 2015-07-10 08:30
@marbemac: what you describe would mean to do a deep diff on the data and this is precisely what Baobab intents to avoid. However I might add a little option making the updates "pure" (probably not the good word) so they check shallowly if something has changed in the data before firing an update. But this should probably be the job of components to do so with PureRender etc. rather than the tree's job.

**Comment by Yomguithereal** [comment] 2015-07-10 08:32
@marbemac: concerning your second question, you should probably use the array shorthand if you want to do something of the kind:

```js
{
  $computedData: [
    ['data'],
    ...
    function() { /* Getter */ }
  ]
}
```

**Comment by Yomguithereal** [comment] 2015-07-10 08:33
@ivan-kleshnin: still, it would be strange not to enable the user to prepend/unshift to a list because we provide a reverse method.

**Comment by Yomguithereal** [comment] 2015-07-10 08:39
Hello @frontengineer: some people use facets to perform data fetching but this has its own shortcomings. I personally prefer the approach described [here](https://github.com/Yomguithereal/baobab/issues/188#issuecomment-110497360) (with the description of the abstraction).

The general idea is to plug a listener on the tree listening to `get` events and, whenever some part of your app gets a precise path of the tree and receives something you think is not "valid", then you trigger data-fetching.

```js
// When the app starts, its data is null because it
// hasn't been fetched yet.
const tree = new Baobab({
  data: {
    messages: null
  }
});

// Let's listen the tree `get` events
tree.on('get', function({data: {path, data}})) {
  // We have the gotten `path`
  // and the gotten `data`

  // We can check here if this data should be
  // what it is at this path, and if not,
  // we fire data fetching
});
```

**Comment by ivan-kleshnin** [comment] 2015-07-10 08:45
> still, it would be strange not to enable the user to prepend/unshift to a list because we provide a reverse method.

I was proposing to have `append`, `prepend` and `concat`. As there is no common name for "`preconcat`" operation it should be manually reproduced. `revert` is very low-level and may come in handy in many situations.

**Comment by Yomguithereal** [comment] 2015-07-10 09:32
Ok, I see your point. I'll add `concat`. But, maybe I should stick with `push/unshift` rather than `append/prepend` to stick with JavaScript naming and not throw current users off by making the evolution too hard on their code?

**Comment by ivan-kleshnin** [comment] 2015-07-10 09:48
> But, maybe I should stick with push/unshift rather than append/prepend to stick with JavaScript naming and not throw current users off by making the evolution too hard on their code?

I dunno. I never use mutable operations in normal JS code, so I never parallel DB layer (baobab) with business layer where everything should be stateless and immutable. They are strongly separated in my mind. So I have no strong opinion on this.

**Comment by Yomguithereal** [comment] 2015-07-16 10:57
I am writing docs for v2 right now. Will probably ship a release candidate soon.

**Comment by Yomguithereal** [comment] 2015-07-16 14:09
Updated docs are now available [here](https://github.com/Yomguithereal/baobab/tree/v2).

**Comment by markuplab** [comment] 2015-07-20 17:27
When you plan release baobab@2.0.0?)

**Comment by Yomguithereal** [comment] 2015-07-21 08:27
Probably in the following weeks @markuplab. The API is nearly stabilized on `baobab@dev` if you want to try it out.

**Comment by hyusetiawan** [comment] 2015-07-27 06:46
will it be backwards compatible with v1? or should a new development be based on v2 instead?

**Comment by Yomguithereal** [comment] 2015-07-27 09:51
Hello @hyusetiawan. The v2 won't be backwards compatible as per semver recommandations. However, depending on your use cases, it's possible you wouldn't have much things to change from v1 to v2. Check out [this](https://github.com/Yomguithereal/baobab/tree/v2#migration) migration helper for better information.

You could base your dev on v2 already. Some things remain to be fixed but the version is now more or less stable.

**Comment by tinchoz49** [comment] 2015-07-29 20:15
this an amazing library and is going to be better with the `baobab-deku` on the v2! :+1:

**Comment by Yomguithereal** [comment] 2015-07-29 20:38
Thanks @tinchoz49. I'm just waiting for the next version of deku before starting `baobab-deku`.

**Comment by saulshanabrook** [comment] 2015-07-29 21:15
@tinchoz49 Where is `baobab-deku`?

**Comment by Yomguithereal** [comment] 2015-08-13 12:16
Released `baobab@2.0.0-rc1`.

**Comment by Yomguithereal** [comment] 2015-08-13 12:17
I am working on `baobab-deku` @saulshanabrook. My issue is the lack of a react-like `context` to be able to provide something completely correct for deku.

**Comment by markuplab** [comment] 2015-08-25 05:55
When u plan release 2.0.0 stable?

**Comment by Yomguithereal** [comment] 2015-08-26 12:50
Hello @markuplab. I intent to release a stable version soon but I want to be sure I don't make any mistakes on the v2's concepts themselves.

**Comment by frontengineer** [comment] 2015-08-26 14:30
@christianalfoni @ivan-kleshnin  @Yomguithereal  Thanks to all your great discussion and work...while I've been waiting for V2, I've learned RxJS and created a todo app.  It's pretty interesting library and approach. Now I am thinking I may try Baobab (data structure) with RxJS (data/event flow).  I feels like overlap between the cursors and observables...but I do like both libraries...so we'll see.

**Comment by DylanPiercey** [comment] 2015-08-27 21:56
What does setting a facet on the fly look like? Is it possible to update a facet to look at different data or use a different function?

**Comment by Yomguithereal** [comment] 2015-08-31 09:58
Hello @DylanPiercey. The intention is indeed to let the user modify the facets or even delete them easily by changing the watched paths or the getter function.

This would look like that in fact:

```js
tree.set('path', {cursors: {one: ['one']}, get: function() {}});
```

**Comment by DylanPiercey** [comment] 2015-09-03 18:41
@Yomguithereal it would be cool if there was a way to update individual cursors or the getter separately. What are your thoughts on this?

**Closed** 2015-09-28 14:47 UTC
Labels: enhancement, question
